#!/usr/bin/env python3
"""Generates src/graph/properties/keys.rs: one interned key per distinct
property id declared anywhere in vendor/elk-swift (`Property<T>("id", ...)`).

elk-swift stores property values in `[String: Any]` maps keyed by the id
string, so two `Property` objects with the same id share a slot. Upleft interns
the ids into `PropKey`s with the same sharing."""
import glob, os, re, sys

root = os.path.join(os.path.dirname(__file__), "../../../vendor/elk-swift/Sources/ElkSwift")
ids = []
for f in sorted(glob.glob(os.path.join(root, "**/*.swift"), recursive=True)):
    s = open(f).read()
    for m in re.finditer(r'Property<[^(]*?>\s*\(\s*"([^"]*)"', s, re.S):
        if m.group(1) not in ids:
            ids.append(m.group(1))

def const_name(pid):
    p = pid
    prefix = ""
    if p.startswith("org.eclipse.elk."):
        p = p[len("org.eclipse.elk."):]
        prefix = "ELK_"
    p = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', p)
    p = re.sub(r'[^A-Za-z0-9]+', '_', p)
    return prefix + p.upper()

names = [const_name(i) for i in ids]
assert len(set(names)) == len(names), "name collision"
out = []
out.append("//! Interned property ids. Generated by `tools/gen_prop_keys.py` from every")
out.append("//! `Property<T>(\"id\", ...)` declaration in vendor/elk-swift; do not edit.")
out.append("//!")
out.append("//! elk-swift keys property maps by the id string, so two `Property` objects")
out.append("//! with the same id share a slot. A `PropKey` is that id, interned.")
out.append("")
out.append("/// An interned property id.")
out.append("#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, PartialOrd, Ord)]")
out.append("pub struct PropKey(pub u16);")
out.append("")
for i, (pid, n) in enumerate(zip(ids, names)):
    out.append(f"/// `{pid}`")
    out.append(f"pub const {n}: PropKey = PropKey({i});")
out.append("")
out.append(f"pub const COUNT: usize = {len(ids)};")
out.append("")
out.append("/// The id string of each key.")
out.append(f"pub static NAMES: [&str; {len(ids)}] = [")
for pid in ids:
    out.append(f"    \"{pid}\",")
out.append("];")
out.append("")
out.append("/// The key for an id string, if any property declares it.")
out.append("pub fn lookup(id: &str) -> Option<PropKey> {")
out.append("    Some(match id {")
for pid, n in zip(ids, names):
    out.append(f"        \"{pid}\" => {n},")
out.append("        _ => return None,")
out.append("    })")
out.append("}")
out.append("")
out.append("impl PropKey {")
out.append("    pub fn name(self) -> &'static str {")
out.append("        NAMES[self.0 as usize]")
out.append("    }")
out.append("}")
open(os.path.join(os.path.dirname(__file__), "../src/org/eclipse/elk/graph/properties/keys.rs"), "w").write("\n".join(out) + "\n")
print(len(ids), "keys")
