// Generates crates/swift-text/src/tables.rs from the Swift runtime's own
// Unicode data, so Upleft's Character/CharacterSet semantics are Downright's
// by construction rather than by agreement between two Unicode versions. The
// `unicode` conformance suite re-checks every table against the runtime.
//
//   swiftc -O crates/swift-text/scripts/gen-unicode-tables.swift -o /tmp/gen && /tmp/gen > crates/swift-text/src/tables.rs
import Foundation

func ranges(_ member: (Unicode.Scalar) -> Bool) -> [(UInt32, UInt32)] {
    var out: [(UInt32, UInt32)] = []
    var start: UInt32? = nil
    var previous: UInt32 = 0
    for value in UInt32(0)...0x10FFFF {
        guard let scalar = Unicode.Scalar(value) else { continue }
        if member(scalar) {
            if let s = start, previous + 1 == value || (previous == 0xD7FF && value == 0xE000) {
                _ = s
            } else {
                if let s = start { out.append((s, previous)) }
                start = value
            }
            previous = value
        } else if let s = start {
            out.append((s, previous))
            start = nil
        }
    }
    if let s = start { out.append((s, previous)) }
    return out
}

func hex(_ v: UInt32) -> String { "0x" + String(v, radix: 16, uppercase: true) }

func emit(_ name: String, _ doc: String, _ table: [(UInt32, UInt32)]) {
    print("/// \(doc)")
    print("pub static \(name): &[(u32, u32)] = &[")
    var line = "   "
    for (lo, hi) in table {
        let item = " (\(hex(lo)), \(hex(hi))),"
        if line.count + item.count > 100 { print(line); line = "   " }
        line += item
    }
    if line != "   " { print(line) }
    print("];\n")
}

func rustString(_ s: String) -> String {
    var out = "\""
    for scalar in s.unicodeScalars {
        if scalar.value < 0x80 && scalar.value >= 0x20 && scalar != "\"" && scalar != "\\" {
            out.unicodeScalars.append(scalar)
        } else {
            out += "\\u{" + String(scalar.value, radix: 16, uppercase: true) + "}"
        }
    }
    return out + "\""
}

print("""
// @generated by crates/swift-text/scripts/gen-unicode-tables.swift from the Swift runtime
// (\(ProcessInfo.processInfo.operatingSystemVersionString)). Do not edit.
//
// Inclusive scalar ranges, ascending and non-overlapping (surrogates excluded).

""")
emit("ALPHABETIC", "`Unicode.Scalar.Properties.isAlphabetic` — `Character.isLetter` tests the first scalar.", ranges { $0.properties.isAlphabetic })
emit("NUMERIC", "`Unicode.Scalar.Properties.numericType != nil` — `Character.isNumber` tests the first scalar.", ranges { $0.properties.numericType != nil })
emit("WHITE_SPACE", "`Unicode.Scalar.Properties.isWhitespace` — `Character.isWhitespace` tests the first scalar.", ranges { $0.properties.isWhitespace })
emit("GRAPHEME_EXTEND", "`Unicode.Scalar.Properties.isGraphemeExtend`.", ranges { $0.properties.isGraphemeExtend })
emit("CS_WHITESPACES", "`CharacterSet.whitespaces` membership.", ranges { CharacterSet.whitespaces.contains($0) })
emit("CS_WHITESPACES_AND_NEWLINES", "`CharacterSet.whitespacesAndNewlines` membership.", ranges { CharacterSet.whitespacesAndNewlines.contains($0) })
emit("CS_NEWLINES", "`CharacterSet.newlines` membership.", ranges { CharacterSet.newlines.contains($0) })
emit("CS_ALPHANUMERICS", "`CharacterSet.alphanumerics` membership.", ranges { CharacterSet.alphanumerics.contains($0) })
emit("PUNCTUATION", "General category P* — `Character.isPunctuation` tests the first scalar.", ranges {
    switch $0.properties.generalCategory {
    case .connectorPunctuation, .dashPunctuation, .openPunctuation, .closePunctuation,
         .initialPunctuation, .finalPunctuation, .otherPunctuation: return true
    default: return false
    }
})
emit("SYMBOL", "General category S* — `Character.isSymbol` tests the first scalar.", ranges {
    switch $0.properties.generalCategory {
    case .mathSymbol, .currencySymbol, .modifierSymbol, .otherSymbol: return true
    default: return false
    }
})
emit("UPPERCASE", "`Unicode.Scalar.Properties.isUppercase`.", ranges { $0.properties.isUppercase })
emit("LOWERCASE", "`Unicode.Scalar.Properties.isLowercase`.", ranges { $0.properties.isLowercase })
emit("CASED", "`Unicode.Scalar.Properties.isCased`.", ranges { $0.properties.isCased })

// Full lowercase mappings that differ from the identity.
print("/// `Unicode.Scalar.Properties.lowercaseMapping` wherever it is not the scalar itself.")
print("pub static LOWERCASE_MAPPING: &[(u32, &str)] = &[")
for value in UInt32(0)...0x10FFFF {
    guard let scalar = Unicode.Scalar(value) else { continue }
    let mapping = scalar.properties.lowercaseMapping
    if mapping != String(scalar) || mapping.unicodeScalars.count != 1 || mapping.unicodeScalars.first! != scalar {
        print("    (\(hex(value)), \(rustString(mapping))),")
    }
}
print("];\n")

print("/// `Unicode.Scalar.Properties.uppercaseMapping` wherever it is not the scalar itself.")
print("pub static UPPERCASE_MAPPING: &[(u32, &str)] = &[")
for value in UInt32(0)...0x10FFFF {
    guard let scalar = Unicode.Scalar(value) else { continue }
    let mapping = scalar.properties.uppercaseMapping
    if mapping.unicodeScalars.count != 1 || mapping.unicodeScalars.first! != scalar {
        print("    (\(hex(value)), \(rustString(mapping))),")
    }
}
print("];\n")

// Scalars whose canonical decomposition is a single ASCII scalar (e.g. KELVIN
// SIGN → K). Swift's Character equality and NSString's non-literal search both
// work up to canonical equivalence, so these match their ASCII counterparts.
print("/// Non-ASCII scalars canonically equivalent to a single ASCII scalar.")
print("pub static ASCII_SINGLETONS: &[(u32, u8)] = &[")
for value in UInt32(0x80)...0x10FFFF {
    guard let scalar = Unicode.Scalar(value) else { continue }
    let decomposed = String(scalar).decomposedStringWithCanonicalMapping.unicodeScalars
    if decomposed.count == 1, let only = decomposed.first, only.isASCII {
        print("    (\(hex(value)), \(only.value)),")
    }
}
print("];")
