//! Interned property ids. Generated by `tools/gen_prop_keys.py` from every
//! `Property<T>("id", ...)` declaration in vendor/elk-swift; do not edit.
//!
//! elk-swift keys property maps by the id string, so two `Property` objects
//! with the same id share a slot. A `PropKey` is that id, interned.

/// An interned property id.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, PartialOrd, Ord)]
pub struct PropKey(pub u16);

/// `portRatioOrPosition`
pub const PORT_RATIO_OR_POSITION: PropKey = PropKey(0);
/// `edgelabelcenterednessanalysis.includelabel`
pub const EDGELABELCENTEREDNESSANALYSIS_INCLUDELABEL: PropKey = PropKey(1);
/// `separateLayerConnections`
pub const SEPARATE_LAYER_CONNECTIONS: PropKey = PropKey(2);
/// `origin`
pub const ORIGIN: PropKey = PropKey(3);
/// `originalBendpoints`
pub const ORIGINAL_BENDPOINTS: PropKey = PropKey(4);
/// `originalDummyNodePosition`
pub const ORIGINAL_DUMMY_NODE_POSITION: PropKey = PropKey(5);
/// `originalPortConstraints`
pub const ORIGINAL_PORT_CONSTRAINTS: PropKey = PropKey(6);
/// `longEdgeSource`
pub const LONG_EDGE_SOURCE: PropKey = PropKey(7);
/// `longEdgeTarget`
pub const LONG_EDGE_TARGET: PropKey = PropKey(8);
/// `longEdgeTargetNode`
pub const LONG_EDGE_TARGET_NODE: PropKey = PropKey(9);
/// `longEdgeHasLabelDummies`
pub const LONG_EDGE_HAS_LABEL_DUMMIES: PropKey = PropKey(10);
/// `inLayerLayoutUnit`
pub const IN_LAYER_LAYOUT_UNIT: PropKey = PropKey(11);
/// `inLayerSuccessorConstraint`
pub const IN_LAYER_SUCCESSOR_CONSTRAINT: PropKey = PropKey(12);
/// `inLayerConstraint`
pub const IN_LAYER_CONSTRAINT: PropKey = PropKey(13);
/// `graphProperties`
pub const GRAPH_PROPERTIES: PropKey = PropKey(14);
/// `barycenterAssociates`
pub const BARYCENTER_ASSOCIATES: PropKey = PropKey(15);
/// `modelOrder`
pub const MODEL_ORDER: PropKey = PropKey(16);
/// `modelOrder.maximum`
pub const MODEL_ORDER_MAXIMUM: PropKey = PropKey(17);
/// `modelOrderGroups.cb.number`
pub const MODEL_ORDER_GROUPS_CB_NUMBER: PropKey = PropKey(18);
/// `targetNode.modelOrder`
pub const TARGET_NODE_MODEL_ORDER: PropKey = PropKey(19);
/// `cyclic`
pub const CYCLIC: PropKey = PropKey(20);
/// `reversed`
pub const REVERSED: PropKey = PropKey(21);
/// `isPartOfCycle`
pub const IS_PART_OF_CYCLE: PropKey = PropKey(22);
/// `inputCollect`
pub const INPUT_COLLECT: PropKey = PropKey(23);
/// `outputCollect`
pub const OUTPUT_COLLECT: PropKey = PropKey(24);
/// `spacings`
pub const SPACINGS: PropKey = PropKey(25);
/// `portDummy`
pub const PORT_DUMMY: PropKey = PropKey(26);
/// `processors`
pub const PROCESSORS: PropKey = PropKey(27);
/// `tarjan.lowlink`
pub const TARJAN_LOWLINK: PropKey = PropKey(28);
/// `tarjan.id`
pub const TARJAN_ID: PropKey = PropKey(29);
/// `tarjan.onStack`
pub const TARJAN_ON_STACK: PropKey = PropKey(30);
/// `extPort.side`
pub const EXT_PORT_SIDE: PropKey = PropKey(31);
/// `extPort.connections`
pub const EXT_PORT_CONNECTIONS: PropKey = PropKey(32);
/// `extPort.size`
pub const EXT_PORT_SIZE: PropKey = PropKey(33);
/// `endLabel.edge`
pub const END_LABEL_EDGE: PropKey = PropKey(34);
/// `endLabels`
pub const END_LABELS: PropKey = PropKey(35);
/// `edgeConstraint`
pub const EDGE_CONSTRAINT: PropKey = PropKey(36);
/// `topComments`
pub const TOP_COMMENTS: PropKey = PropKey(37);
/// `bottomComments`
pub const BOTTOM_COMMENTS: PropKey = PropKey(38);
/// `commentConnPort`
pub const COMMENT_CONN_PORT: PropKey = PropKey(39);
/// `spline.route.start`
pub const SPLINE_ROUTE_START: PropKey = PropKey(40);
/// `spline.edgeChain`
pub const SPLINE_EDGE_CHAIN: PropKey = PropKey(41);
/// `spline.nsPortY`
pub const SPLINE_NS_PORT_Y: PropKey = PropKey(42);
/// `spline.survivingEdge`
pub const SPLINE_SURVIVING_EDGE: PropKey = PropKey(43);
/// `dummy`
pub const DUMMY: PropKey = PropKey(44);
/// `compoundNode`
pub const COMPOUND_NODE: PropKey = PropKey(45);
/// `crossHierarchyMap`
pub const CROSS_HIERARCHY_MAP: PropKey = PropKey(46);
/// `insideConnections`
pub const INSIDE_CONNECTIONS: PropKey = PropKey(47);
/// `coordinateSystemOrigin`
pub const COORDINATE_SYSTEM_ORIGIN: PropKey = PropKey(48);
/// `bb.upLeft`
pub const BB_UP_LEFT: PropKey = PropKey(49);
/// `bb.lowRight`
pub const BB_LOW_RIGHT: PropKey = PropKey(50);
/// `random`
pub const RANDOM: PropKey = PropKey(51);
/// `labelSide`
pub const LABEL_SIDE: PropKey = PropKey(52);
/// `maxEdgeThickness`
pub const MAX_EDGE_THICKNESS: PropKey = PropKey(53);
/// `targetOffset`
pub const TARGET_OFFSET: PropKey = PropKey(54);
/// `unnecessaryBendpoints`
pub const UNNECESSARY_BENDPOINTS: PropKey = PropKey(55);
/// `originalLabelEdge`
pub const ORIGINAL_LABEL_EDGE: PropKey = PropKey(56);
/// `representedLabels`
pub const REPRESENTED_LABELS: PropKey = PropKey(57);
/// `hiddenNodes`
pub const HIDDEN_NODES: PropKey = PropKey(58);
/// `originalOppositePort`
pub const ORIGINAL_OPPOSITE_PORT: PropKey = PropKey(59);
/// `longEdgeBeforeLabelDummy`
pub const LONG_EDGE_BEFORE_LABEL_DUMMY: PropKey = PropKey(60);
/// `extPort.replacedDummies`
pub const EXT_PORT_REPLACED_DUMMIES: PropKey = PropKey(61);
/// `extPort.replacedDummy`
pub const EXT_PORT_REPLACED_DUMMY: PropKey = PropKey(62);
/// `crossingHint`
pub const CROSSING_HINT: PropKey = PropKey(63);
/// `selfLoopHolder`
pub const SELF_LOOP_HOLDER: PropKey = PropKey(64);
/// `org.eclipse.elk.layered.layering.layerConstraint`
pub const ELK_LAYERED_LAYERING_LAYER_CONSTRAINT: PropKey = PropKey(65);
/// `org.eclipse.elk.edgeLabels.placement`
pub const ELK_EDGE_LABELS_PLACEMENT: PropKey = PropKey(66);
/// `org.eclipse.elk.nodeLabels.placement`
pub const ELK_NODE_LABELS_PLACEMENT: PropKey = PropKey(67);
/// `org.eclipse.elk.portConstraints`
pub const ELK_PORT_CONSTRAINTS: PropKey = PropKey(68);
/// `org.eclipse.elk.layered.thoroughness`
pub const ELK_LAYERED_THOROUGHNESS: PropKey = PropKey(69);
/// `org.eclipse.elk.spacing.edgeEdge`
pub const ELK_SPACING_EDGE_EDGE: PropKey = PropKey(70);
/// `org.eclipse.elk.spacing.nodeNode`
pub const ELK_SPACING_NODE_NODE: PropKey = PropKey(71);
/// `org.eclipse.elk.spacing.portPort`
pub const ELK_SPACING_PORT_PORT: PropKey = PropKey(72);
/// `org.eclipse.elk.spacing.portsSurrounding`
pub const ELK_SPACING_PORTS_SURROUNDING: PropKey = PropKey(73);
/// `org.eclipse.elk.spacing.edgeNode`
pub const ELK_SPACING_EDGE_NODE: PropKey = PropKey(74);
/// `org.eclipse.elk.spacing.edgeLabel`
pub const ELK_SPACING_EDGE_LABEL: PropKey = PropKey(75);
/// `org.eclipse.elk.spacing.labelLabel`
pub const ELK_SPACING_LABEL_LABEL: PropKey = PropKey(76);
/// `org.eclipse.elk.spacing.labelPort`
pub const ELK_SPACING_LABEL_PORT: PropKey = PropKey(77);
/// `org.eclipse.elk.spacing.labelNode`
pub const ELK_SPACING_LABEL_NODE: PropKey = PropKey(78);
/// `org.eclipse.elk.spacing.labelPortHorizontal`
pub const ELK_SPACING_LABEL_PORT_HORIZONTAL: PropKey = PropKey(79);
/// `org.eclipse.elk.spacing.labelPortVertical`
pub const ELK_SPACING_LABEL_PORT_VERTICAL: PropKey = PropKey(80);
/// `org.eclipse.elk.layered.spacing.edgeEdgeBetweenLayers`
pub const ELK_LAYERED_SPACING_EDGE_EDGE_BETWEEN_LAYERS: PropKey = PropKey(81);
/// `org.eclipse.elk.layered.spacing.edgeNodeBetweenLayers`
pub const ELK_LAYERED_SPACING_EDGE_NODE_BETWEEN_LAYERS: PropKey = PropKey(82);
/// `org.eclipse.elk.layered.spacing.nodeNodeBetweenLayers`
pub const ELK_LAYERED_SPACING_NODE_NODE_BETWEEN_LAYERS: PropKey = PropKey(83);
/// `org.eclipse.elk.spacing.commentComment`
pub const ELK_SPACING_COMMENT_COMMENT: PropKey = PropKey(84);
/// `org.eclipse.elk.spacing.commentNode`
pub const ELK_SPACING_COMMENT_NODE: PropKey = PropKey(85);
/// `org.eclipse.elk.spacing.componentComponent`
pub const ELK_SPACING_COMPONENT_COMPONENT: PropKey = PropKey(86);
/// `org.eclipse.elk.spacing.baseValue`
pub const ELK_SPACING_BASE_VALUE: PropKey = PropKey(87);
/// `org.eclipse.elk.priority`
pub const ELK_PRIORITY: PropKey = PropKey(88);
/// `org.eclipse.elk.layered.priority.direction`
pub const ELK_LAYERED_PRIORITY_DIRECTION: PropKey = PropKey(89);
/// `org.eclipse.elk.layered.priority.shortness`
pub const ELK_LAYERED_PRIORITY_SHORTNESS: PropKey = PropKey(90);
/// `org.eclipse.elk.layered.priority.straightness`
pub const ELK_LAYERED_PRIORITY_STRAIGHTNESS: PropKey = PropKey(91);
/// `org.eclipse.elk.layered.interactiveReferencePoint`
pub const ELK_LAYERED_INTERACTIVE_REFERENCE_POINT: PropKey = PropKey(92);
/// `org.eclipse.elk.layered.nodePlacement.favorStraightEdges`
pub const ELK_LAYERED_NODE_PLACEMENT_FAVOR_STRAIGHT_EDGES: PropKey = PropKey(93);
/// `org.eclipse.elk.layered.nodePlacement.bk.edgeStraightening`
pub const ELK_LAYERED_NODE_PLACEMENT_BK_EDGE_STRAIGHTENING: PropKey = PropKey(94);
/// `org.eclipse.elk.layered.nodePlacement.bk.fixedAlignment`
pub const ELK_LAYERED_NODE_PLACEMENT_BK_FIXED_ALIGNMENT: PropKey = PropKey(95);
/// `org.eclipse.elk.layered.nodePlacement.linearSegments.deflectionDampening`
pub const ELK_LAYERED_NODE_PLACEMENT_LINEAR_SEGMENTS_DEFLECTION_DAMPENING: PropKey = PropKey(96);
/// `org.eclipse.elk.layered.nodePlacement.strategy`
pub const ELK_LAYERED_NODE_PLACEMENT_STRATEGY: PropKey = PropKey(97);
/// `org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cycleBreakingId`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CYCLE_BREAKING_ID: PropKey = PropKey(98);
/// `org.eclipse.elk.layered.considerModelOrder.groupModelOrder.crossingMinimizationId`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CROSSING_MINIMIZATION_ID: PropKey = PropKey(99);
/// `org.eclipse.elk.layered.considerModelOrder.groupModelOrder.componentGroupId`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_COMPONENT_GROUP_ID: PropKey = PropKey(100);
/// `org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbGroupOrderStrategy`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CB_GROUP_ORDER_STRATEGY: PropKey = PropKey(101);
/// `org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cmGroupOrderStrategy`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CM_GROUP_ORDER_STRATEGY: PropKey = PropKey(102);
/// `org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cmEnforcedGroupOrders`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CM_ENFORCED_GROUP_ORDERS: PropKey = PropKey(103);
/// `org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbPreferredSourceId`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CB_PREFERRED_SOURCE_ID: PropKey = PropKey(104);
/// `org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbPreferredTargetId`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CB_PREFERRED_TARGET_ID: PropKey = PropKey(105);
/// `org.eclipse.elk.direction`
pub const ELK_DIRECTION: PropKey = PropKey(106);
/// `org.eclipse.elk.layered.layering.layerId`
pub const ELK_LAYERED_LAYERING_LAYER_ID: PropKey = PropKey(107);
/// `org.eclipse.elk.layered.crossingMinimization.inLayerPredOf`
pub const ELK_LAYERED_CROSSING_MINIMIZATION_IN_LAYER_PRED_OF: PropKey = PropKey(108);
/// `org.eclipse.elk.layered.crossingMinimization.inLayerSuccOf`
pub const ELK_LAYERED_CROSSING_MINIMIZATION_IN_LAYER_SUCC_OF: PropKey = PropKey(109);
/// `org.eclipse.elk.nodeSize.constraints`
pub const ELK_NODE_SIZE_CONSTRAINTS: PropKey = PropKey(110);
/// `org.eclipse.elk.nodeSize.options`
pub const ELK_NODE_SIZE_OPTIONS: PropKey = PropKey(111);
/// `org.eclipse.elk.nodeSize.minimum`
pub const ELK_NODE_SIZE_MINIMUM: PropKey = PropKey(112);
/// `org.eclipse.elk.nodeSize.fixedGraphSize`
pub const ELK_NODE_SIZE_FIXED_GRAPH_SIZE: PropKey = PropKey(113);
/// `org.eclipse.elk.noLayout`
pub const ELK_NO_LAYOUT: PropKey = PropKey(114);
/// `org.eclipse.elk.layered.layering.layerChoiceConstraint`
pub const ELK_LAYERED_LAYERING_LAYER_CHOICE_CONSTRAINT: PropKey = PropKey(115);
/// `org.eclipse.elk.portLabels.placement`
pub const ELK_PORT_LABELS_PLACEMENT: PropKey = PropKey(116);
/// `org.eclipse.elk.portLabels.nextToPortIfPossible`
pub const ELK_PORT_LABELS_NEXT_TO_PORT_IF_POSSIBLE: PropKey = PropKey(117);
/// `org.eclipse.elk.portAlignment.default`
pub const ELK_PORT_ALIGNMENT_DEFAULT: PropKey = PropKey(118);
/// `org.eclipse.elk.port.side`
pub const ELK_PORT_SIDE: PropKey = PropKey(119);
/// `org.eclipse.elk.port.borderOffset`
pub const ELK_PORT_BORDER_OFFSET: PropKey = PropKey(120);
/// `org.eclipse.elk.port.anchor`
pub const ELK_PORT_ANCHOR: PropKey = PropKey(121);
/// `org.eclipse.elk.port.index`
pub const ELK_PORT_INDEX: PropKey = PropKey(122);
/// `org.eclipse.elk.padding`
pub const ELK_PADDING: PropKey = PropKey(123);
/// `org.eclipse.elk.alignment`
pub const ELK_ALIGNMENT: PropKey = PropKey(124);
/// `org.eclipse.elk.nodeLabels.padding`
pub const ELK_NODE_LABELS_PADDING: PropKey = PropKey(125);
/// `org.eclipse.elk.aspectRatio`
pub const ELK_ASPECT_RATIO: PropKey = PropKey(126);
/// `org.eclipse.elk.position`
pub const ELK_POSITION: PropKey = PropKey(127);
/// `org.eclipse.elk.insideSelfLoops.activate`
pub const ELK_INSIDE_SELF_LOOPS_ACTIVATE: PropKey = PropKey(128);
/// `org.eclipse.elk.insideSelfLoops.yo`
pub const ELK_INSIDE_SELF_LOOPS_YO: PropKey = PropKey(129);
/// `org.eclipse.elk.separateConnectedComponents`
pub const ELK_SEPARATE_CONNECTED_COMPONENTS: PropKey = PropKey(130);
/// `org.eclipse.elk.contentAlignment`
pub const ELK_CONTENT_ALIGNMENT: PropKey = PropKey(131);
/// `org.eclipse.elk.edgeRouting`
pub const ELK_EDGE_ROUTING: PropKey = PropKey(132);
/// `org.eclipse.elk.edgeRouting.splines.mode`
pub const ELK_EDGE_ROUTING_SPLINES_MODE: PropKey = PropKey(133);
/// `org.eclipse.elk.layered.edgeRouting.selfLoopDistribution`
pub const ELK_LAYERED_EDGE_ROUTING_SELF_LOOP_DISTRIBUTION: PropKey = PropKey(134);
/// `org.eclipse.elk.layered.edgeRouting.selfLoopOrdering`
pub const ELK_LAYERED_EDGE_ROUTING_SELF_LOOP_ORDERING: PropKey = PropKey(135);
/// `org.eclipse.elk.layered.spacing.nodeSelfLoop`
pub const ELK_LAYERED_SPACING_NODE_SELF_LOOP: PropKey = PropKey(136);
/// `org.eclipse.elk.layered.edgeRouting.polyline.slopedEdgeZoneWidth`
pub const ELK_LAYERED_EDGE_ROUTING_POLYLINE_SLOPED_EDGE_ZONE_WIDTH: PropKey = PropKey(137);
/// `org.eclipse.elk.edge.thickness`
pub const ELK_EDGE_THICKNESS: PropKey = PropKey(138);
/// `org.eclipse.elk.junctionPoints`
pub const ELK_JUNCTION_POINTS: PropKey = PropKey(139);
/// `org.eclipse.elk.commentBox`
pub const ELK_COMMENT_BOX: PropKey = PropKey(140);
/// `org.eclipse.elk.hypernode`
pub const ELK_HYPERNODE: PropKey = PropKey(141);
/// `org.eclipse.elk.hierarchyHandling`
pub const ELK_HIERARCHY_HANDLING: PropKey = PropKey(142);
/// `org.eclipse.elk.interactive`
pub const ELK_INTERACTIVE: PropKey = PropKey(143);
/// `org.eclipse.elk.layered.edgeLabels.sideSelection`
pub const ELK_LAYERED_EDGE_LABELS_SIDE_SELECTION: PropKey = PropKey(144);
/// `org.eclipse.elk.edgeLabels.inline`
pub const ELK_EDGE_LABELS_INLINE: PropKey = PropKey(145);
/// `org.eclipse.elk.layered.unnecessaryBendpoints`
pub const ELK_LAYERED_UNNECESSARY_BENDPOINTS: PropKey = PropKey(146);
/// `org.eclipse.elk.layered.directionCongruency`
pub const ELK_LAYERED_DIRECTION_CONGRUENCY: PropKey = PropKey(147);
/// `org.eclipse.elk.layered.feedbackEdges`
pub const ELK_LAYERED_FEEDBACK_EDGES: PropKey = PropKey(148);
/// `org.eclipse.elk.layered.mergeEdges`
pub const ELK_LAYERED_MERGE_EDGES: PropKey = PropKey(149);
/// `org.eclipse.elk.layered.mergeHierarchyEdges`
pub const ELK_LAYERED_MERGE_HIERARCHY_EDGES: PropKey = PropKey(150);
/// `org.eclipse.elk.randomSeed`
pub const ELK_RANDOM_SEED: PropKey = PropKey(151);
/// `org.eclipse.elk.layered.minWidth`
pub const ELK_LAYERED_MIN_WIDTH: PropKey = PropKey(152);
/// `org.eclipse.elk.layered.minHeight`
pub const ELK_LAYERED_MIN_HEIGHT: PropKey = PropKey(153);
/// `org.eclipse.elk.layered.crossingMinimization.strategy`
pub const ELK_LAYERED_CROSSING_MINIMIZATION_STRATEGY: PropKey = PropKey(154);
/// `org.eclipse.elk.layered.crossingMinimization.greedySwitchActivationThreshold`
pub const ELK_LAYERED_CROSSING_MINIMIZATION_GREEDY_SWITCH_ACTIVATION_THRESHOLD: PropKey = PropKey(155);
/// `org.eclipse.elk.layered.crossingMinimization.greedySwitchType`
pub const ELK_LAYERED_CROSSING_MINIMIZATION_GREEDY_SWITCH_TYPE: PropKey = PropKey(156);
/// `org.eclipse.elk.layered.crossingMinimization.greedySwitchHierarchicalType`
pub const ELK_LAYERED_CROSSING_MINIMIZATION_GREEDY_SWITCH_HIERARCHICAL_TYPE: PropKey = PropKey(157);
/// `org.eclipse.elk.layered.crossingMinimization.semiInteractive`
pub const ELK_LAYERED_CROSSING_MINIMIZATION_SEMI_INTERACTIVE: PropKey = PropKey(158);
/// `org.eclipse.elk.layered.crossingMinimization.forceNodeModelOrder`
pub const ELK_LAYERED_CROSSING_MINIMIZATION_FORCE_NODE_MODEL_ORDER: PropKey = PropKey(159);
/// `org.eclipse.elk.layered.crossingMinimization.hierarchicalSweepiness`
pub const ELK_LAYERED_CROSSING_MINIMIZATION_HIERARCHICAL_SWEEPINESS: PropKey = PropKey(160);
/// `org.eclipse.elk.layered.crossingMinimization.positionChoiceConstraint`
pub const ELK_LAYERED_CROSSING_MINIMIZATION_POSITION_CHOICE_CONSTRAINT: PropKey = PropKey(161);
/// `org.eclipse.elk.layered.crossingMinimization.positionId`
pub const ELK_LAYERED_CROSSING_MINIMIZATION_POSITION_ID: PropKey = PropKey(162);
/// `org.eclipse.elk.layered.considerModelOrder.strategy`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_STRATEGY: PropKey = PropKey(163);
/// `org.eclipse.elk.layered.considerModelOrder.crossingCounterNodeInfluence`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_CROSSING_COUNTER_NODE_INFLUENCE: PropKey = PropKey(164);
/// `org.eclipse.elk.layered.considerModelOrder.crossingCounterPortInfluence`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_CROSSING_COUNTER_PORT_INFLUENCE: PropKey = PropKey(165);
/// `org.eclipse.elk.layered.considerModelOrder.noModelOrder`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_NO_MODEL_ORDER: PropKey = PropKey(166);
/// `org.eclipse.elk.layered.considerModelOrder.components`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_COMPONENTS: PropKey = PropKey(167);
/// `org.eclipse.elk.layered.considerModelOrder.longEdgeStrategy`
pub const ELK_LAYERED_CONSIDER_MODEL_ORDER_LONG_EDGE_STRATEGY: PropKey = PropKey(168);
/// `org.eclipse.elk.layered.layering.strategy`
pub const ELK_LAYERED_LAYERING_STRATEGY: PropKey = PropKey(169);
/// `org.eclipse.elk.layered.layering.nodePromotion.strategy`
pub const ELK_LAYERED_LAYERING_NODE_PROMOTION_STRATEGY: PropKey = PropKey(170);
/// `org.eclipse.elk.layered.layering.coffmanGraham.layerBound`
pub const ELK_LAYERED_LAYERING_COFFMAN_GRAHAM_LAYER_BOUND: PropKey = PropKey(171);
/// `org.eclipse.elk.layered.layerUnzippingStrategy`
pub const ELK_LAYERED_LAYER_UNZIPPING_STRATEGY: PropKey = PropKey(172);
/// `org.eclipse.elk.layered.cycleBreaking.strategy`
pub const ELK_LAYERED_CYCLE_BREAKING_STRATEGY: PropKey = PropKey(173);
/// `org.eclipse.elk.layered.allowNonFlowPortsToSwitchSides`
pub const ELK_LAYERED_ALLOW_NON_FLOW_PORTS_TO_SWITCH_SIDES: PropKey = PropKey(174);
/// `org.eclipse.elk.layered.compaction.postCompaction.strategy`
pub const ELK_LAYERED_COMPACTION_POST_COMPACTION_STRATEGY: PropKey = PropKey(175);
/// `org.eclipse.elk.layered.compaction.postCompaction.constraints`
pub const ELK_LAYERED_COMPACTION_POST_COMPACTION_CONSTRAINTS: PropKey = PropKey(176);
/// `org.eclipse.elk.layered.compaction.connectedComponents`
pub const ELK_LAYERED_COMPACTION_CONNECTED_COMPONENTS: PropKey = PropKey(177);
/// `org.eclipse.elk.layered.highDegreeNodes.treatment`
pub const ELK_LAYERED_HIGH_DEGREE_NODES_TREATMENT: PropKey = PropKey(178);
/// `org.eclipse.elk.layered.highDegreeNodes.threshold`
pub const ELK_LAYERED_HIGH_DEGREE_NODES_THRESHOLD: PropKey = PropKey(179);
/// `org.eclipse.elk.layered.highDegreeNodes.treeHeight`
pub const ELK_LAYERED_HIGH_DEGREE_NODES_TREE_HEIGHT: PropKey = PropKey(180);
/// `org.eclipse.elk.partitioning.activate`
pub const ELK_PARTITIONING_ACTIVATE: PropKey = PropKey(181);
/// `org.eclipse.elk.layered.generatePositionAndLayerIds`
pub const ELK_LAYERED_GENERATE_POSITION_AND_LAYER_IDS: PropKey = PropKey(182);
/// `org.eclipse.elk.layered.portSortingStrategy`
pub const ELK_LAYERED_PORT_SORTING_STRATEGY: PropKey = PropKey(183);
/// `org.eclipse.elk.layered.edgeLabels.centerLabelPlacementStrategy`
pub const ELK_LAYERED_EDGE_LABELS_CENTER_LABEL_PLACEMENT_STRATEGY: PropKey = PropKey(184);
/// `org.eclipse.elk.layered.wrapping.strategy`
pub const ELK_LAYERED_WRAPPING_STRATEGY: PropKey = PropKey(185);
/// `org.eclipse.elk.layered.wrapping.additionalEdgeSpacing`
pub const ELK_LAYERED_WRAPPING_ADDITIONAL_EDGE_SPACING: PropKey = PropKey(186);
/// `org.eclipse.elk.layered.wrapping.correctionFactor`
pub const ELK_LAYERED_WRAPPING_CORRECTION_FACTOR: PropKey = PropKey(187);
/// `org.eclipse.elk.layered.wrapping.cutting.strategy`
pub const ELK_LAYERED_WRAPPING_CUTTING_STRATEGY: PropKey = PropKey(188);
/// `org.eclipse.elk.layered.wrapping.cutting.cuts`
pub const ELK_LAYERED_WRAPPING_CUTTING_CUTS: PropKey = PropKey(189);
/// `org.eclipse.elk.layered.wrapping.cutting.msd.freedom`
pub const ELK_LAYERED_WRAPPING_CUTTING_MSD_FREEDOM: PropKey = PropKey(190);
/// `org.eclipse.elk.layered.wrapping.validify.strategy`
pub const ELK_LAYERED_WRAPPING_VALIDIFY_STRATEGY: PropKey = PropKey(191);
/// `org.eclipse.elk.layered.wrapping.validify.forbiddenIndices`
pub const ELK_LAYERED_WRAPPING_VALIDIFY_FORBIDDEN_INDICES: PropKey = PropKey(192);
/// `org.eclipse.elk.layered.wrapping.multiEdge.improveCuts`
pub const ELK_LAYERED_WRAPPING_MULTI_EDGE_IMPROVE_CUTS: PropKey = PropKey(193);
/// `org.eclipse.elk.layered.wrapping.multiEdge.improveWrappedEdges`
pub const ELK_LAYERED_WRAPPING_MULTI_EDGE_IMPROVE_WRAPPED_EDGES: PropKey = PropKey(194);
/// `org.eclipse.elk.layered.wrapping.multiEdge.distancePenalty`
pub const ELK_LAYERED_WRAPPING_MULTI_EDGE_DISTANCE_PENALTY: PropKey = PropKey(195);
/// `org.eclipse.elk.layered.nodePlacement.networkSimplex.nodeFlexibility`
pub const ELK_LAYERED_NODE_PLACEMENT_NETWORK_SIMPLEX_NODE_FLEXIBILITY: PropKey = PropKey(196);
/// `org.eclipse.elk.layered.nodePlacement.networkSimplex.nodeFlexibility.default`
pub const ELK_LAYERED_NODE_PLACEMENT_NETWORK_SIMPLEX_NODE_FLEXIBILITY_DEFAULT: PropKey = PropKey(197);
/// `org.eclipse.elk.labels.labelManager`
pub const ELK_LABELS_LABEL_MANAGER: PropKey = PropKey(198);
/// `org.eclipse.elk.alg.layered.p3order.sortedPorts.todo`
pub const ELK_ALG_LAYERED_P3ORDER_SORTED_PORTS_TODO: PropKey = PropKey(199);
/// `org.eclipse.elk.algorithm`
pub const ELK_ALGORITHM: PropKey = PropKey(200);
/// `org.eclipse.elk.resolvedAlgorithm`
pub const ELK_RESOLVED_ALGORITHM: PropKey = PropKey(201);
/// `org.eclipse.elk.scaleFactor`
pub const ELK_SCALE_FACTOR: PropKey = PropKey(202);
/// `org.eclipse.elk.animate`
pub const ELK_ANIMATE: PropKey = PropKey(203);
/// `org.eclipse.elk.progressBar`
pub const ELK_PROGRESS_BAR: PropKey = PropKey(204);
/// `org.eclipse.elk.zoomToFit`
pub const ELK_ZOOM_TO_FIT: PropKey = PropKey(205);
/// `org.eclipse.elk.layoutAncestors`
pub const ELK_LAYOUT_ANCESTORS: PropKey = PropKey(206);
/// `org.eclipse.elk.spacing.individual`
pub const ELK_SPACING_INDIVIDUAL: PropKey = PropKey(207);
/// `org.eclipse.elk.portLabels.treatAsGroup`
pub const ELK_PORT_LABELS_TREAT_AS_GROUP: PropKey = PropKey(208);
/// `org.eclipse.elk.portAlignment.north`
pub const ELK_PORT_ALIGNMENT_NORTH: PropKey = PropKey(209);
/// `org.eclipse.elk.portAlignment.south`
pub const ELK_PORT_ALIGNMENT_SOUTH: PropKey = PropKey(210);
/// `org.eclipse.elk.portAlignment.east`
pub const ELK_PORT_ALIGNMENT_EAST: PropKey = PropKey(211);
/// `org.eclipse.elk.portAlignment.west`
pub const ELK_PORT_ALIGNMENT_WEST: PropKey = PropKey(212);
/// `org.eclipse.elk.edgeType`
pub const ELK_EDGE_TYPE: PropKey = PropKey(213);
/// `org.eclipse.elk.margins`
pub const ELK_MARGINS: PropKey = PropKey(214);
/// `org.eclipse.elk.json.edgeCoords`
pub const ELK_JSON_EDGE_COORDS: PropKey = PropKey(215);
/// `org.eclipse.elk.json.shapeCoords`
pub const ELK_JSON_SHAPE_COORDS: PropKey = PropKey(216);
/// `org.eclipse.elk.topdownLayout`
pub const ELK_TOPDOWN_LAYOUT: PropKey = PropKey(217);
/// `org.eclipse.elk.topdown.nodeType`
pub const ELK_TOPDOWN_NODE_TYPE: PropKey = PropKey(218);
/// `org.eclipse.elk.topdown.scaleFactor`
pub const ELK_TOPDOWN_SCALE_FACTOR: PropKey = PropKey(219);
/// `org.eclipse.elk.topdown.scaleCap`
pub const ELK_TOPDOWN_SCALE_CAP: PropKey = PropKey(220);
/// `org.eclipse.elk.topdown.hierarchicalNodeWidth`
pub const ELK_TOPDOWN_HIERARCHICAL_NODE_WIDTH: PropKey = PropKey(221);
/// `org.eclipse.elk.topdown.hierarchicalNodeAspectRatio`
pub const ELK_TOPDOWN_HIERARCHICAL_NODE_ASPECT_RATIO: PropKey = PropKey(222);
/// `org.eclipse.elk.topdown.sizeApproximator`
pub const ELK_TOPDOWN_SIZE_APPROXIMATOR: PropKey = PropKey(223);
/// `org.eclipse.elk.topdown.sizeCategories`
pub const ELK_TOPDOWN_SIZE_CATEGORIES: PropKey = PropKey(224);
/// `org.eclipse.elk.topdown.sizeCategories.hierarchicalNodeWeight`
pub const ELK_TOPDOWN_SIZE_CATEGORIES_HIERARCHICAL_NODE_WEIGHT: PropKey = PropKey(225);
/// `org.eclipse.elk.childAreaWidth`
pub const ELK_CHILD_AREA_WIDTH: PropKey = PropKey(226);
/// `org.eclipse.elk.childAreaHeight`
pub const ELK_CHILD_AREA_HEIGHT: PropKey = PropKey(227);
/// `org.eclipse.elk.labelSide`
pub const ELK_LABEL_SIDE: PropKey = PropKey(228);
/// `org.eclipse.elk.addLayoutConfig`
pub const ELK_ADD_LAYOUT_CONFIG: PropKey = PropKey(229);

pub const COUNT: usize = 230;

/// The id string of each key.
pub static NAMES: [&str; 230] = [
    "portRatioOrPosition",
    "edgelabelcenterednessanalysis.includelabel",
    "separateLayerConnections",
    "origin",
    "originalBendpoints",
    "originalDummyNodePosition",
    "originalPortConstraints",
    "longEdgeSource",
    "longEdgeTarget",
    "longEdgeTargetNode",
    "longEdgeHasLabelDummies",
    "inLayerLayoutUnit",
    "inLayerSuccessorConstraint",
    "inLayerConstraint",
    "graphProperties",
    "barycenterAssociates",
    "modelOrder",
    "modelOrder.maximum",
    "modelOrderGroups.cb.number",
    "targetNode.modelOrder",
    "cyclic",
    "reversed",
    "isPartOfCycle",
    "inputCollect",
    "outputCollect",
    "spacings",
    "portDummy",
    "processors",
    "tarjan.lowlink",
    "tarjan.id",
    "tarjan.onStack",
    "extPort.side",
    "extPort.connections",
    "extPort.size",
    "endLabel.edge",
    "endLabels",
    "edgeConstraint",
    "topComments",
    "bottomComments",
    "commentConnPort",
    "spline.route.start",
    "spline.edgeChain",
    "spline.nsPortY",
    "spline.survivingEdge",
    "dummy",
    "compoundNode",
    "crossHierarchyMap",
    "insideConnections",
    "coordinateSystemOrigin",
    "bb.upLeft",
    "bb.lowRight",
    "random",
    "labelSide",
    "maxEdgeThickness",
    "targetOffset",
    "unnecessaryBendpoints",
    "originalLabelEdge",
    "representedLabels",
    "hiddenNodes",
    "originalOppositePort",
    "longEdgeBeforeLabelDummy",
    "extPort.replacedDummies",
    "extPort.replacedDummy",
    "crossingHint",
    "selfLoopHolder",
    "org.eclipse.elk.layered.layering.layerConstraint",
    "org.eclipse.elk.edgeLabels.placement",
    "org.eclipse.elk.nodeLabels.placement",
    "org.eclipse.elk.portConstraints",
    "org.eclipse.elk.layered.thoroughness",
    "org.eclipse.elk.spacing.edgeEdge",
    "org.eclipse.elk.spacing.nodeNode",
    "org.eclipse.elk.spacing.portPort",
    "org.eclipse.elk.spacing.portsSurrounding",
    "org.eclipse.elk.spacing.edgeNode",
    "org.eclipse.elk.spacing.edgeLabel",
    "org.eclipse.elk.spacing.labelLabel",
    "org.eclipse.elk.spacing.labelPort",
    "org.eclipse.elk.spacing.labelNode",
    "org.eclipse.elk.spacing.labelPortHorizontal",
    "org.eclipse.elk.spacing.labelPortVertical",
    "org.eclipse.elk.layered.spacing.edgeEdgeBetweenLayers",
    "org.eclipse.elk.layered.spacing.edgeNodeBetweenLayers",
    "org.eclipse.elk.layered.spacing.nodeNodeBetweenLayers",
    "org.eclipse.elk.spacing.commentComment",
    "org.eclipse.elk.spacing.commentNode",
    "org.eclipse.elk.spacing.componentComponent",
    "org.eclipse.elk.spacing.baseValue",
    "org.eclipse.elk.priority",
    "org.eclipse.elk.layered.priority.direction",
    "org.eclipse.elk.layered.priority.shortness",
    "org.eclipse.elk.layered.priority.straightness",
    "org.eclipse.elk.layered.interactiveReferencePoint",
    "org.eclipse.elk.layered.nodePlacement.favorStraightEdges",
    "org.eclipse.elk.layered.nodePlacement.bk.edgeStraightening",
    "org.eclipse.elk.layered.nodePlacement.bk.fixedAlignment",
    "org.eclipse.elk.layered.nodePlacement.linearSegments.deflectionDampening",
    "org.eclipse.elk.layered.nodePlacement.strategy",
    "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cycleBreakingId",
    "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.crossingMinimizationId",
    "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.componentGroupId",
    "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbGroupOrderStrategy",
    "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cmGroupOrderStrategy",
    "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cmEnforcedGroupOrders",
    "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbPreferredSourceId",
    "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbPreferredTargetId",
    "org.eclipse.elk.direction",
    "org.eclipse.elk.layered.layering.layerId",
    "org.eclipse.elk.layered.crossingMinimization.inLayerPredOf",
    "org.eclipse.elk.layered.crossingMinimization.inLayerSuccOf",
    "org.eclipse.elk.nodeSize.constraints",
    "org.eclipse.elk.nodeSize.options",
    "org.eclipse.elk.nodeSize.minimum",
    "org.eclipse.elk.nodeSize.fixedGraphSize",
    "org.eclipse.elk.noLayout",
    "org.eclipse.elk.layered.layering.layerChoiceConstraint",
    "org.eclipse.elk.portLabels.placement",
    "org.eclipse.elk.portLabels.nextToPortIfPossible",
    "org.eclipse.elk.portAlignment.default",
    "org.eclipse.elk.port.side",
    "org.eclipse.elk.port.borderOffset",
    "org.eclipse.elk.port.anchor",
    "org.eclipse.elk.port.index",
    "org.eclipse.elk.padding",
    "org.eclipse.elk.alignment",
    "org.eclipse.elk.nodeLabels.padding",
    "org.eclipse.elk.aspectRatio",
    "org.eclipse.elk.position",
    "org.eclipse.elk.insideSelfLoops.activate",
    "org.eclipse.elk.insideSelfLoops.yo",
    "org.eclipse.elk.separateConnectedComponents",
    "org.eclipse.elk.contentAlignment",
    "org.eclipse.elk.edgeRouting",
    "org.eclipse.elk.edgeRouting.splines.mode",
    "org.eclipse.elk.layered.edgeRouting.selfLoopDistribution",
    "org.eclipse.elk.layered.edgeRouting.selfLoopOrdering",
    "org.eclipse.elk.layered.spacing.nodeSelfLoop",
    "org.eclipse.elk.layered.edgeRouting.polyline.slopedEdgeZoneWidth",
    "org.eclipse.elk.edge.thickness",
    "org.eclipse.elk.junctionPoints",
    "org.eclipse.elk.commentBox",
    "org.eclipse.elk.hypernode",
    "org.eclipse.elk.hierarchyHandling",
    "org.eclipse.elk.interactive",
    "org.eclipse.elk.layered.edgeLabels.sideSelection",
    "org.eclipse.elk.edgeLabels.inline",
    "org.eclipse.elk.layered.unnecessaryBendpoints",
    "org.eclipse.elk.layered.directionCongruency",
    "org.eclipse.elk.layered.feedbackEdges",
    "org.eclipse.elk.layered.mergeEdges",
    "org.eclipse.elk.layered.mergeHierarchyEdges",
    "org.eclipse.elk.randomSeed",
    "org.eclipse.elk.layered.minWidth",
    "org.eclipse.elk.layered.minHeight",
    "org.eclipse.elk.layered.crossingMinimization.strategy",
    "org.eclipse.elk.layered.crossingMinimization.greedySwitchActivationThreshold",
    "org.eclipse.elk.layered.crossingMinimization.greedySwitchType",
    "org.eclipse.elk.layered.crossingMinimization.greedySwitchHierarchicalType",
    "org.eclipse.elk.layered.crossingMinimization.semiInteractive",
    "org.eclipse.elk.layered.crossingMinimization.forceNodeModelOrder",
    "org.eclipse.elk.layered.crossingMinimization.hierarchicalSweepiness",
    "org.eclipse.elk.layered.crossingMinimization.positionChoiceConstraint",
    "org.eclipse.elk.layered.crossingMinimization.positionId",
    "org.eclipse.elk.layered.considerModelOrder.strategy",
    "org.eclipse.elk.layered.considerModelOrder.crossingCounterNodeInfluence",
    "org.eclipse.elk.layered.considerModelOrder.crossingCounterPortInfluence",
    "org.eclipse.elk.layered.considerModelOrder.noModelOrder",
    "org.eclipse.elk.layered.considerModelOrder.components",
    "org.eclipse.elk.layered.considerModelOrder.longEdgeStrategy",
    "org.eclipse.elk.layered.layering.strategy",
    "org.eclipse.elk.layered.layering.nodePromotion.strategy",
    "org.eclipse.elk.layered.layering.coffmanGraham.layerBound",
    "org.eclipse.elk.layered.layerUnzippingStrategy",
    "org.eclipse.elk.layered.cycleBreaking.strategy",
    "org.eclipse.elk.layered.allowNonFlowPortsToSwitchSides",
    "org.eclipse.elk.layered.compaction.postCompaction.strategy",
    "org.eclipse.elk.layered.compaction.postCompaction.constraints",
    "org.eclipse.elk.layered.compaction.connectedComponents",
    "org.eclipse.elk.layered.highDegreeNodes.treatment",
    "org.eclipse.elk.layered.highDegreeNodes.threshold",
    "org.eclipse.elk.layered.highDegreeNodes.treeHeight",
    "org.eclipse.elk.partitioning.activate",
    "org.eclipse.elk.layered.generatePositionAndLayerIds",
    "org.eclipse.elk.layered.portSortingStrategy",
    "org.eclipse.elk.layered.edgeLabels.centerLabelPlacementStrategy",
    "org.eclipse.elk.layered.wrapping.strategy",
    "org.eclipse.elk.layered.wrapping.additionalEdgeSpacing",
    "org.eclipse.elk.layered.wrapping.correctionFactor",
    "org.eclipse.elk.layered.wrapping.cutting.strategy",
    "org.eclipse.elk.layered.wrapping.cutting.cuts",
    "org.eclipse.elk.layered.wrapping.cutting.msd.freedom",
    "org.eclipse.elk.layered.wrapping.validify.strategy",
    "org.eclipse.elk.layered.wrapping.validify.forbiddenIndices",
    "org.eclipse.elk.layered.wrapping.multiEdge.improveCuts",
    "org.eclipse.elk.layered.wrapping.multiEdge.improveWrappedEdges",
    "org.eclipse.elk.layered.wrapping.multiEdge.distancePenalty",
    "org.eclipse.elk.layered.nodePlacement.networkSimplex.nodeFlexibility",
    "org.eclipse.elk.layered.nodePlacement.networkSimplex.nodeFlexibility.default",
    "org.eclipse.elk.labels.labelManager",
    "org.eclipse.elk.alg.layered.p3order.sortedPorts.todo",
    "org.eclipse.elk.algorithm",
    "org.eclipse.elk.resolvedAlgorithm",
    "org.eclipse.elk.scaleFactor",
    "org.eclipse.elk.animate",
    "org.eclipse.elk.progressBar",
    "org.eclipse.elk.zoomToFit",
    "org.eclipse.elk.layoutAncestors",
    "org.eclipse.elk.spacing.individual",
    "org.eclipse.elk.portLabels.treatAsGroup",
    "org.eclipse.elk.portAlignment.north",
    "org.eclipse.elk.portAlignment.south",
    "org.eclipse.elk.portAlignment.east",
    "org.eclipse.elk.portAlignment.west",
    "org.eclipse.elk.edgeType",
    "org.eclipse.elk.margins",
    "org.eclipse.elk.json.edgeCoords",
    "org.eclipse.elk.json.shapeCoords",
    "org.eclipse.elk.topdownLayout",
    "org.eclipse.elk.topdown.nodeType",
    "org.eclipse.elk.topdown.scaleFactor",
    "org.eclipse.elk.topdown.scaleCap",
    "org.eclipse.elk.topdown.hierarchicalNodeWidth",
    "org.eclipse.elk.topdown.hierarchicalNodeAspectRatio",
    "org.eclipse.elk.topdown.sizeApproximator",
    "org.eclipse.elk.topdown.sizeCategories",
    "org.eclipse.elk.topdown.sizeCategories.hierarchicalNodeWeight",
    "org.eclipse.elk.childAreaWidth",
    "org.eclipse.elk.childAreaHeight",
    "org.eclipse.elk.labelSide",
    "org.eclipse.elk.addLayoutConfig",
];

/// The key for an id string, if any property declares it.
pub fn lookup(id: &str) -> Option<PropKey> {
    Some(match id {
        "portRatioOrPosition" => PORT_RATIO_OR_POSITION,
        "edgelabelcenterednessanalysis.includelabel" => EDGELABELCENTEREDNESSANALYSIS_INCLUDELABEL,
        "separateLayerConnections" => SEPARATE_LAYER_CONNECTIONS,
        "origin" => ORIGIN,
        "originalBendpoints" => ORIGINAL_BENDPOINTS,
        "originalDummyNodePosition" => ORIGINAL_DUMMY_NODE_POSITION,
        "originalPortConstraints" => ORIGINAL_PORT_CONSTRAINTS,
        "longEdgeSource" => LONG_EDGE_SOURCE,
        "longEdgeTarget" => LONG_EDGE_TARGET,
        "longEdgeTargetNode" => LONG_EDGE_TARGET_NODE,
        "longEdgeHasLabelDummies" => LONG_EDGE_HAS_LABEL_DUMMIES,
        "inLayerLayoutUnit" => IN_LAYER_LAYOUT_UNIT,
        "inLayerSuccessorConstraint" => IN_LAYER_SUCCESSOR_CONSTRAINT,
        "inLayerConstraint" => IN_LAYER_CONSTRAINT,
        "graphProperties" => GRAPH_PROPERTIES,
        "barycenterAssociates" => BARYCENTER_ASSOCIATES,
        "modelOrder" => MODEL_ORDER,
        "modelOrder.maximum" => MODEL_ORDER_MAXIMUM,
        "modelOrderGroups.cb.number" => MODEL_ORDER_GROUPS_CB_NUMBER,
        "targetNode.modelOrder" => TARGET_NODE_MODEL_ORDER,
        "cyclic" => CYCLIC,
        "reversed" => REVERSED,
        "isPartOfCycle" => IS_PART_OF_CYCLE,
        "inputCollect" => INPUT_COLLECT,
        "outputCollect" => OUTPUT_COLLECT,
        "spacings" => SPACINGS,
        "portDummy" => PORT_DUMMY,
        "processors" => PROCESSORS,
        "tarjan.lowlink" => TARJAN_LOWLINK,
        "tarjan.id" => TARJAN_ID,
        "tarjan.onStack" => TARJAN_ON_STACK,
        "extPort.side" => EXT_PORT_SIDE,
        "extPort.connections" => EXT_PORT_CONNECTIONS,
        "extPort.size" => EXT_PORT_SIZE,
        "endLabel.edge" => END_LABEL_EDGE,
        "endLabels" => END_LABELS,
        "edgeConstraint" => EDGE_CONSTRAINT,
        "topComments" => TOP_COMMENTS,
        "bottomComments" => BOTTOM_COMMENTS,
        "commentConnPort" => COMMENT_CONN_PORT,
        "spline.route.start" => SPLINE_ROUTE_START,
        "spline.edgeChain" => SPLINE_EDGE_CHAIN,
        "spline.nsPortY" => SPLINE_NS_PORT_Y,
        "spline.survivingEdge" => SPLINE_SURVIVING_EDGE,
        "dummy" => DUMMY,
        "compoundNode" => COMPOUND_NODE,
        "crossHierarchyMap" => CROSS_HIERARCHY_MAP,
        "insideConnections" => INSIDE_CONNECTIONS,
        "coordinateSystemOrigin" => COORDINATE_SYSTEM_ORIGIN,
        "bb.upLeft" => BB_UP_LEFT,
        "bb.lowRight" => BB_LOW_RIGHT,
        "random" => RANDOM,
        "labelSide" => LABEL_SIDE,
        "maxEdgeThickness" => MAX_EDGE_THICKNESS,
        "targetOffset" => TARGET_OFFSET,
        "unnecessaryBendpoints" => UNNECESSARY_BENDPOINTS,
        "originalLabelEdge" => ORIGINAL_LABEL_EDGE,
        "representedLabels" => REPRESENTED_LABELS,
        "hiddenNodes" => HIDDEN_NODES,
        "originalOppositePort" => ORIGINAL_OPPOSITE_PORT,
        "longEdgeBeforeLabelDummy" => LONG_EDGE_BEFORE_LABEL_DUMMY,
        "extPort.replacedDummies" => EXT_PORT_REPLACED_DUMMIES,
        "extPort.replacedDummy" => EXT_PORT_REPLACED_DUMMY,
        "crossingHint" => CROSSING_HINT,
        "selfLoopHolder" => SELF_LOOP_HOLDER,
        "org.eclipse.elk.layered.layering.layerConstraint" => ELK_LAYERED_LAYERING_LAYER_CONSTRAINT,
        "org.eclipse.elk.edgeLabels.placement" => ELK_EDGE_LABELS_PLACEMENT,
        "org.eclipse.elk.nodeLabels.placement" => ELK_NODE_LABELS_PLACEMENT,
        "org.eclipse.elk.portConstraints" => ELK_PORT_CONSTRAINTS,
        "org.eclipse.elk.layered.thoroughness" => ELK_LAYERED_THOROUGHNESS,
        "org.eclipse.elk.spacing.edgeEdge" => ELK_SPACING_EDGE_EDGE,
        "org.eclipse.elk.spacing.nodeNode" => ELK_SPACING_NODE_NODE,
        "org.eclipse.elk.spacing.portPort" => ELK_SPACING_PORT_PORT,
        "org.eclipse.elk.spacing.portsSurrounding" => ELK_SPACING_PORTS_SURROUNDING,
        "org.eclipse.elk.spacing.edgeNode" => ELK_SPACING_EDGE_NODE,
        "org.eclipse.elk.spacing.edgeLabel" => ELK_SPACING_EDGE_LABEL,
        "org.eclipse.elk.spacing.labelLabel" => ELK_SPACING_LABEL_LABEL,
        "org.eclipse.elk.spacing.labelPort" => ELK_SPACING_LABEL_PORT,
        "org.eclipse.elk.spacing.labelNode" => ELK_SPACING_LABEL_NODE,
        "org.eclipse.elk.spacing.labelPortHorizontal" => ELK_SPACING_LABEL_PORT_HORIZONTAL,
        "org.eclipse.elk.spacing.labelPortVertical" => ELK_SPACING_LABEL_PORT_VERTICAL,
        "org.eclipse.elk.layered.spacing.edgeEdgeBetweenLayers" => ELK_LAYERED_SPACING_EDGE_EDGE_BETWEEN_LAYERS,
        "org.eclipse.elk.layered.spacing.edgeNodeBetweenLayers" => ELK_LAYERED_SPACING_EDGE_NODE_BETWEEN_LAYERS,
        "org.eclipse.elk.layered.spacing.nodeNodeBetweenLayers" => ELK_LAYERED_SPACING_NODE_NODE_BETWEEN_LAYERS,
        "org.eclipse.elk.spacing.commentComment" => ELK_SPACING_COMMENT_COMMENT,
        "org.eclipse.elk.spacing.commentNode" => ELK_SPACING_COMMENT_NODE,
        "org.eclipse.elk.spacing.componentComponent" => ELK_SPACING_COMPONENT_COMPONENT,
        "org.eclipse.elk.spacing.baseValue" => ELK_SPACING_BASE_VALUE,
        "org.eclipse.elk.priority" => ELK_PRIORITY,
        "org.eclipse.elk.layered.priority.direction" => ELK_LAYERED_PRIORITY_DIRECTION,
        "org.eclipse.elk.layered.priority.shortness" => ELK_LAYERED_PRIORITY_SHORTNESS,
        "org.eclipse.elk.layered.priority.straightness" => ELK_LAYERED_PRIORITY_STRAIGHTNESS,
        "org.eclipse.elk.layered.interactiveReferencePoint" => ELK_LAYERED_INTERACTIVE_REFERENCE_POINT,
        "org.eclipse.elk.layered.nodePlacement.favorStraightEdges" => ELK_LAYERED_NODE_PLACEMENT_FAVOR_STRAIGHT_EDGES,
        "org.eclipse.elk.layered.nodePlacement.bk.edgeStraightening" => ELK_LAYERED_NODE_PLACEMENT_BK_EDGE_STRAIGHTENING,
        "org.eclipse.elk.layered.nodePlacement.bk.fixedAlignment" => ELK_LAYERED_NODE_PLACEMENT_BK_FIXED_ALIGNMENT,
        "org.eclipse.elk.layered.nodePlacement.linearSegments.deflectionDampening" => ELK_LAYERED_NODE_PLACEMENT_LINEAR_SEGMENTS_DEFLECTION_DAMPENING,
        "org.eclipse.elk.layered.nodePlacement.strategy" => ELK_LAYERED_NODE_PLACEMENT_STRATEGY,
        "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cycleBreakingId" => ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CYCLE_BREAKING_ID,
        "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.crossingMinimizationId" => ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CROSSING_MINIMIZATION_ID,
        "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.componentGroupId" => ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_COMPONENT_GROUP_ID,
        "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbGroupOrderStrategy" => ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CB_GROUP_ORDER_STRATEGY,
        "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cmGroupOrderStrategy" => ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CM_GROUP_ORDER_STRATEGY,
        "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cmEnforcedGroupOrders" => ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CM_ENFORCED_GROUP_ORDERS,
        "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbPreferredSourceId" => ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CB_PREFERRED_SOURCE_ID,
        "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbPreferredTargetId" => ELK_LAYERED_CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CB_PREFERRED_TARGET_ID,
        "org.eclipse.elk.direction" => ELK_DIRECTION,
        "org.eclipse.elk.layered.layering.layerId" => ELK_LAYERED_LAYERING_LAYER_ID,
        "org.eclipse.elk.layered.crossingMinimization.inLayerPredOf" => ELK_LAYERED_CROSSING_MINIMIZATION_IN_LAYER_PRED_OF,
        "org.eclipse.elk.layered.crossingMinimization.inLayerSuccOf" => ELK_LAYERED_CROSSING_MINIMIZATION_IN_LAYER_SUCC_OF,
        "org.eclipse.elk.nodeSize.constraints" => ELK_NODE_SIZE_CONSTRAINTS,
        "org.eclipse.elk.nodeSize.options" => ELK_NODE_SIZE_OPTIONS,
        "org.eclipse.elk.nodeSize.minimum" => ELK_NODE_SIZE_MINIMUM,
        "org.eclipse.elk.nodeSize.fixedGraphSize" => ELK_NODE_SIZE_FIXED_GRAPH_SIZE,
        "org.eclipse.elk.noLayout" => ELK_NO_LAYOUT,
        "org.eclipse.elk.layered.layering.layerChoiceConstraint" => ELK_LAYERED_LAYERING_LAYER_CHOICE_CONSTRAINT,
        "org.eclipse.elk.portLabels.placement" => ELK_PORT_LABELS_PLACEMENT,
        "org.eclipse.elk.portLabels.nextToPortIfPossible" => ELK_PORT_LABELS_NEXT_TO_PORT_IF_POSSIBLE,
        "org.eclipse.elk.portAlignment.default" => ELK_PORT_ALIGNMENT_DEFAULT,
        "org.eclipse.elk.port.side" => ELK_PORT_SIDE,
        "org.eclipse.elk.port.borderOffset" => ELK_PORT_BORDER_OFFSET,
        "org.eclipse.elk.port.anchor" => ELK_PORT_ANCHOR,
        "org.eclipse.elk.port.index" => ELK_PORT_INDEX,
        "org.eclipse.elk.padding" => ELK_PADDING,
        "org.eclipse.elk.alignment" => ELK_ALIGNMENT,
        "org.eclipse.elk.nodeLabels.padding" => ELK_NODE_LABELS_PADDING,
        "org.eclipse.elk.aspectRatio" => ELK_ASPECT_RATIO,
        "org.eclipse.elk.position" => ELK_POSITION,
        "org.eclipse.elk.insideSelfLoops.activate" => ELK_INSIDE_SELF_LOOPS_ACTIVATE,
        "org.eclipse.elk.insideSelfLoops.yo" => ELK_INSIDE_SELF_LOOPS_YO,
        "org.eclipse.elk.separateConnectedComponents" => ELK_SEPARATE_CONNECTED_COMPONENTS,
        "org.eclipse.elk.contentAlignment" => ELK_CONTENT_ALIGNMENT,
        "org.eclipse.elk.edgeRouting" => ELK_EDGE_ROUTING,
        "org.eclipse.elk.edgeRouting.splines.mode" => ELK_EDGE_ROUTING_SPLINES_MODE,
        "org.eclipse.elk.layered.edgeRouting.selfLoopDistribution" => ELK_LAYERED_EDGE_ROUTING_SELF_LOOP_DISTRIBUTION,
        "org.eclipse.elk.layered.edgeRouting.selfLoopOrdering" => ELK_LAYERED_EDGE_ROUTING_SELF_LOOP_ORDERING,
        "org.eclipse.elk.layered.spacing.nodeSelfLoop" => ELK_LAYERED_SPACING_NODE_SELF_LOOP,
        "org.eclipse.elk.layered.edgeRouting.polyline.slopedEdgeZoneWidth" => ELK_LAYERED_EDGE_ROUTING_POLYLINE_SLOPED_EDGE_ZONE_WIDTH,
        "org.eclipse.elk.edge.thickness" => ELK_EDGE_THICKNESS,
        "org.eclipse.elk.junctionPoints" => ELK_JUNCTION_POINTS,
        "org.eclipse.elk.commentBox" => ELK_COMMENT_BOX,
        "org.eclipse.elk.hypernode" => ELK_HYPERNODE,
        "org.eclipse.elk.hierarchyHandling" => ELK_HIERARCHY_HANDLING,
        "org.eclipse.elk.interactive" => ELK_INTERACTIVE,
        "org.eclipse.elk.layered.edgeLabels.sideSelection" => ELK_LAYERED_EDGE_LABELS_SIDE_SELECTION,
        "org.eclipse.elk.edgeLabels.inline" => ELK_EDGE_LABELS_INLINE,
        "org.eclipse.elk.layered.unnecessaryBendpoints" => ELK_LAYERED_UNNECESSARY_BENDPOINTS,
        "org.eclipse.elk.layered.directionCongruency" => ELK_LAYERED_DIRECTION_CONGRUENCY,
        "org.eclipse.elk.layered.feedbackEdges" => ELK_LAYERED_FEEDBACK_EDGES,
        "org.eclipse.elk.layered.mergeEdges" => ELK_LAYERED_MERGE_EDGES,
        "org.eclipse.elk.layered.mergeHierarchyEdges" => ELK_LAYERED_MERGE_HIERARCHY_EDGES,
        "org.eclipse.elk.randomSeed" => ELK_RANDOM_SEED,
        "org.eclipse.elk.layered.minWidth" => ELK_LAYERED_MIN_WIDTH,
        "org.eclipse.elk.layered.minHeight" => ELK_LAYERED_MIN_HEIGHT,
        "org.eclipse.elk.layered.crossingMinimization.strategy" => ELK_LAYERED_CROSSING_MINIMIZATION_STRATEGY,
        "org.eclipse.elk.layered.crossingMinimization.greedySwitchActivationThreshold" => ELK_LAYERED_CROSSING_MINIMIZATION_GREEDY_SWITCH_ACTIVATION_THRESHOLD,
        "org.eclipse.elk.layered.crossingMinimization.greedySwitchType" => ELK_LAYERED_CROSSING_MINIMIZATION_GREEDY_SWITCH_TYPE,
        "org.eclipse.elk.layered.crossingMinimization.greedySwitchHierarchicalType" => ELK_LAYERED_CROSSING_MINIMIZATION_GREEDY_SWITCH_HIERARCHICAL_TYPE,
        "org.eclipse.elk.layered.crossingMinimization.semiInteractive" => ELK_LAYERED_CROSSING_MINIMIZATION_SEMI_INTERACTIVE,
        "org.eclipse.elk.layered.crossingMinimization.forceNodeModelOrder" => ELK_LAYERED_CROSSING_MINIMIZATION_FORCE_NODE_MODEL_ORDER,
        "org.eclipse.elk.layered.crossingMinimization.hierarchicalSweepiness" => ELK_LAYERED_CROSSING_MINIMIZATION_HIERARCHICAL_SWEEPINESS,
        "org.eclipse.elk.layered.crossingMinimization.positionChoiceConstraint" => ELK_LAYERED_CROSSING_MINIMIZATION_POSITION_CHOICE_CONSTRAINT,
        "org.eclipse.elk.layered.crossingMinimization.positionId" => ELK_LAYERED_CROSSING_MINIMIZATION_POSITION_ID,
        "org.eclipse.elk.layered.considerModelOrder.strategy" => ELK_LAYERED_CONSIDER_MODEL_ORDER_STRATEGY,
        "org.eclipse.elk.layered.considerModelOrder.crossingCounterNodeInfluence" => ELK_LAYERED_CONSIDER_MODEL_ORDER_CROSSING_COUNTER_NODE_INFLUENCE,
        "org.eclipse.elk.layered.considerModelOrder.crossingCounterPortInfluence" => ELK_LAYERED_CONSIDER_MODEL_ORDER_CROSSING_COUNTER_PORT_INFLUENCE,
        "org.eclipse.elk.layered.considerModelOrder.noModelOrder" => ELK_LAYERED_CONSIDER_MODEL_ORDER_NO_MODEL_ORDER,
        "org.eclipse.elk.layered.considerModelOrder.components" => ELK_LAYERED_CONSIDER_MODEL_ORDER_COMPONENTS,
        "org.eclipse.elk.layered.considerModelOrder.longEdgeStrategy" => ELK_LAYERED_CONSIDER_MODEL_ORDER_LONG_EDGE_STRATEGY,
        "org.eclipse.elk.layered.layering.strategy" => ELK_LAYERED_LAYERING_STRATEGY,
        "org.eclipse.elk.layered.layering.nodePromotion.strategy" => ELK_LAYERED_LAYERING_NODE_PROMOTION_STRATEGY,
        "org.eclipse.elk.layered.layering.coffmanGraham.layerBound" => ELK_LAYERED_LAYERING_COFFMAN_GRAHAM_LAYER_BOUND,
        "org.eclipse.elk.layered.layerUnzippingStrategy" => ELK_LAYERED_LAYER_UNZIPPING_STRATEGY,
        "org.eclipse.elk.layered.cycleBreaking.strategy" => ELK_LAYERED_CYCLE_BREAKING_STRATEGY,
        "org.eclipse.elk.layered.allowNonFlowPortsToSwitchSides" => ELK_LAYERED_ALLOW_NON_FLOW_PORTS_TO_SWITCH_SIDES,
        "org.eclipse.elk.layered.compaction.postCompaction.strategy" => ELK_LAYERED_COMPACTION_POST_COMPACTION_STRATEGY,
        "org.eclipse.elk.layered.compaction.postCompaction.constraints" => ELK_LAYERED_COMPACTION_POST_COMPACTION_CONSTRAINTS,
        "org.eclipse.elk.layered.compaction.connectedComponents" => ELK_LAYERED_COMPACTION_CONNECTED_COMPONENTS,
        "org.eclipse.elk.layered.highDegreeNodes.treatment" => ELK_LAYERED_HIGH_DEGREE_NODES_TREATMENT,
        "org.eclipse.elk.layered.highDegreeNodes.threshold" => ELK_LAYERED_HIGH_DEGREE_NODES_THRESHOLD,
        "org.eclipse.elk.layered.highDegreeNodes.treeHeight" => ELK_LAYERED_HIGH_DEGREE_NODES_TREE_HEIGHT,
        "org.eclipse.elk.partitioning.activate" => ELK_PARTITIONING_ACTIVATE,
        "org.eclipse.elk.layered.generatePositionAndLayerIds" => ELK_LAYERED_GENERATE_POSITION_AND_LAYER_IDS,
        "org.eclipse.elk.layered.portSortingStrategy" => ELK_LAYERED_PORT_SORTING_STRATEGY,
        "org.eclipse.elk.layered.edgeLabels.centerLabelPlacementStrategy" => ELK_LAYERED_EDGE_LABELS_CENTER_LABEL_PLACEMENT_STRATEGY,
        "org.eclipse.elk.layered.wrapping.strategy" => ELK_LAYERED_WRAPPING_STRATEGY,
        "org.eclipse.elk.layered.wrapping.additionalEdgeSpacing" => ELK_LAYERED_WRAPPING_ADDITIONAL_EDGE_SPACING,
        "org.eclipse.elk.layered.wrapping.correctionFactor" => ELK_LAYERED_WRAPPING_CORRECTION_FACTOR,
        "org.eclipse.elk.layered.wrapping.cutting.strategy" => ELK_LAYERED_WRAPPING_CUTTING_STRATEGY,
        "org.eclipse.elk.layered.wrapping.cutting.cuts" => ELK_LAYERED_WRAPPING_CUTTING_CUTS,
        "org.eclipse.elk.layered.wrapping.cutting.msd.freedom" => ELK_LAYERED_WRAPPING_CUTTING_MSD_FREEDOM,
        "org.eclipse.elk.layered.wrapping.validify.strategy" => ELK_LAYERED_WRAPPING_VALIDIFY_STRATEGY,
        "org.eclipse.elk.layered.wrapping.validify.forbiddenIndices" => ELK_LAYERED_WRAPPING_VALIDIFY_FORBIDDEN_INDICES,
        "org.eclipse.elk.layered.wrapping.multiEdge.improveCuts" => ELK_LAYERED_WRAPPING_MULTI_EDGE_IMPROVE_CUTS,
        "org.eclipse.elk.layered.wrapping.multiEdge.improveWrappedEdges" => ELK_LAYERED_WRAPPING_MULTI_EDGE_IMPROVE_WRAPPED_EDGES,
        "org.eclipse.elk.layered.wrapping.multiEdge.distancePenalty" => ELK_LAYERED_WRAPPING_MULTI_EDGE_DISTANCE_PENALTY,
        "org.eclipse.elk.layered.nodePlacement.networkSimplex.nodeFlexibility" => ELK_LAYERED_NODE_PLACEMENT_NETWORK_SIMPLEX_NODE_FLEXIBILITY,
        "org.eclipse.elk.layered.nodePlacement.networkSimplex.nodeFlexibility.default" => ELK_LAYERED_NODE_PLACEMENT_NETWORK_SIMPLEX_NODE_FLEXIBILITY_DEFAULT,
        "org.eclipse.elk.labels.labelManager" => ELK_LABELS_LABEL_MANAGER,
        "org.eclipse.elk.alg.layered.p3order.sortedPorts.todo" => ELK_ALG_LAYERED_P3ORDER_SORTED_PORTS_TODO,
        "org.eclipse.elk.algorithm" => ELK_ALGORITHM,
        "org.eclipse.elk.resolvedAlgorithm" => ELK_RESOLVED_ALGORITHM,
        "org.eclipse.elk.scaleFactor" => ELK_SCALE_FACTOR,
        "org.eclipse.elk.animate" => ELK_ANIMATE,
        "org.eclipse.elk.progressBar" => ELK_PROGRESS_BAR,
        "org.eclipse.elk.zoomToFit" => ELK_ZOOM_TO_FIT,
        "org.eclipse.elk.layoutAncestors" => ELK_LAYOUT_ANCESTORS,
        "org.eclipse.elk.spacing.individual" => ELK_SPACING_INDIVIDUAL,
        "org.eclipse.elk.portLabels.treatAsGroup" => ELK_PORT_LABELS_TREAT_AS_GROUP,
        "org.eclipse.elk.portAlignment.north" => ELK_PORT_ALIGNMENT_NORTH,
        "org.eclipse.elk.portAlignment.south" => ELK_PORT_ALIGNMENT_SOUTH,
        "org.eclipse.elk.portAlignment.east" => ELK_PORT_ALIGNMENT_EAST,
        "org.eclipse.elk.portAlignment.west" => ELK_PORT_ALIGNMENT_WEST,
        "org.eclipse.elk.edgeType" => ELK_EDGE_TYPE,
        "org.eclipse.elk.margins" => ELK_MARGINS,
        "org.eclipse.elk.json.edgeCoords" => ELK_JSON_EDGE_COORDS,
        "org.eclipse.elk.json.shapeCoords" => ELK_JSON_SHAPE_COORDS,
        "org.eclipse.elk.topdownLayout" => ELK_TOPDOWN_LAYOUT,
        "org.eclipse.elk.topdown.nodeType" => ELK_TOPDOWN_NODE_TYPE,
        "org.eclipse.elk.topdown.scaleFactor" => ELK_TOPDOWN_SCALE_FACTOR,
        "org.eclipse.elk.topdown.scaleCap" => ELK_TOPDOWN_SCALE_CAP,
        "org.eclipse.elk.topdown.hierarchicalNodeWidth" => ELK_TOPDOWN_HIERARCHICAL_NODE_WIDTH,
        "org.eclipse.elk.topdown.hierarchicalNodeAspectRatio" => ELK_TOPDOWN_HIERARCHICAL_NODE_ASPECT_RATIO,
        "org.eclipse.elk.topdown.sizeApproximator" => ELK_TOPDOWN_SIZE_APPROXIMATOR,
        "org.eclipse.elk.topdown.sizeCategories" => ELK_TOPDOWN_SIZE_CATEGORIES,
        "org.eclipse.elk.topdown.sizeCategories.hierarchicalNodeWeight" => ELK_TOPDOWN_SIZE_CATEGORIES_HIERARCHICAL_NODE_WEIGHT,
        "org.eclipse.elk.childAreaWidth" => ELK_CHILD_AREA_WIDTH,
        "org.eclipse.elk.childAreaHeight" => ELK_CHILD_AREA_HEIGHT,
        "org.eclipse.elk.labelSide" => ELK_LABEL_SIDE,
        "org.eclipse.elk.addLayoutConfig" => ELK_ADD_LAYOUT_CONFIG,
        _ => return None,
    })
}

impl PropKey {
    pub fn name(self) -> &'static str {
        NAMES[self.0 as usize]
    }
}
