// Group E golden-data harness (regenerates ../*.golden).
//
// Setup: copy the instrumented elk-swift lab (crates/elk/tools/elklab.sh builds
// it into target/elklab) to a scratch directory, add this file as
// Sources/golden/main.swift, add `.executableTarget(name: "golden",
// dependencies: ["ElkSwift"])` to its Package.swift, and give
// `EndLabelSorter` and `EndLabelPostprocessor` a `package init() {}` in the
// copy (their implicit initializers are internal). Then
// `swift build -c release --product golden` and, in ../,
// `for f in *.json; do .build/release/golden $f > ${f%.json}.golden; done`.
// The specs themselves are generated by gen_specs.py (writes to ../).
import Foundation
import ElkSwift

func norm(_ s: String) -> String { s.lowercased().replacingOccurrences(of: "_", with: "") }
func pick<T>(_ name: String, _ cases: [T]) -> T {
    for c in cases where norm(String(describing: c)) == norm(name) { return c }
    fatalError("unknown case \(name) among \(cases)")
}
func d(_ v: Double) -> String { "\(v)" }
func vec(_ v: KVector) -> String { "(\(d(v.x)),\(d(v.y)))" }
func dbl(_ a: Any?) -> Double { (a as! NSNumber).doubleValue }

var nodesById: [String: LNode] = [:]
var portsById: [String: LPort] = [:]
var edgesById: [String: LEdge] = [:]
var labelsByText: [String: LLabel] = [:]
var idOf: [ObjectIdentifier: String] = [:]
var deferred: [() -> Void] = []

func value(_ type: String, _ raw: Any) -> Any {
    switch type {
    case "Double": return dbl(raw)
    case "Int": return Int(dbl(raw))
    case "Bool": return raw as! Bool
    case "String": return raw as! String
    case "SizeConstraint": return SizeConstraint(rawValue: Int(dbl(raw)))
    case "SizeOptions": return SizeOptions(rawValue: Int(dbl(raw)))
    case "NodeLabelPlacement": return NodeLabelPlacement(rawValue: Int(dbl(raw)))
    case "PortLabelPlacement": return PortLabelPlacement(rawValue: Int(dbl(raw)))
    case "PortConstraints": return pick(raw as! String, [PortConstraints.undefined, .free, .fixedSide, .fixedOrder, .fixedRatio, .fixedPos])
    case "PortAlignment": return pick(raw as! String, [PortAlignment.distributed, .justified, .begin, .center, .end])
    case "Direction": return pick(raw as! String, [Direction.UNDEFINED, .RIGHT, .LEFT, .DOWN, .UP])
    case "EdgeLabelPlacement": return pick(raw as! String, [EdgeLabelPlacement.center, .head, .tail])
    case "EdgeLabelSideSelection": return pick(raw as! String, [EdgeLabelSideSelection.ALWAYS_UP, .ALWAYS_DOWN, .DIRECTION_UP, .DIRECTION_DOWN, .SMART_UP, .SMART_DOWN])
    case "LabelSide": return pick(raw as! String, [LabelSide.UNKNOWN, .ABOVE, .BELOW, .INLINE])
    case "PortSide": return pick(raw as! String, [PortSide.UNDEFINED, .NORTH, .EAST, .SOUTH, .WEST])
    case "ElkPadding": let a = raw as! [Any]; return ElkPadding(dbl(a[0]), dbl(a[1]), dbl(a[2]), dbl(a[3]))
    case "ElkMargin": let a = raw as! [Any]; return ElkMargin(dbl(a[0]), dbl(a[1]), dbl(a[2]), dbl(a[3]))
    case "KVector": let a = raw as! [Any]; return KVector(x: dbl(a[0]), y: dbl(a[1]))
    case "GraphProperties":
        var s = Set<GraphProperties>()
        for n in raw as! [String] { s.insert(pick(n, [GraphProperties.COMMENTS, .EXTERNAL_PORTS, .HYPEREDGES, .HYPERNODES, .NON_FREE_PORTS, .NORTH_SOUTH_PORTS, .SELF_LOOPS, .CENTER_LABELS, .END_LABELS, .PARTITIONS])) }
        return s
    default: fatalError("unknown type \(type)")
    }
}

func setProps(_ holder: MapPropertyHolder, _ props: Any?) {
    for p in (props as? [[Any]]) ?? [] {
        let key = p[0] as! String, type = p[1] as! String
        switch type {
        case "EdgeRef": let id = p[2] as! String; deferred.append { holder.setProperty(key, edgesById[id]!) }
        case "PortRef": let id = p[2] as! String; deferred.append { holder.setProperty(key, portsById[id]!) }
        case "NodeRef": let id = p[2] as! String; deferred.append { holder.setProperty(key, nodesById[id]!) }
        case "LabelRefs": let ids = p[2] as! [String]; deferred.append { holder.setProperty(key, ids.map { labelsByText[$0]! }) }
        default: holder.setProperty(key, value(type, p[2]))
        }
    }
}

func shape(_ s: LShape, _ o: [String: Any]) {
    if let a = o["size"] as? [Any] { s.size = KVector(x: dbl(a[0]), y: dbl(a[1])) }
    if let a = o["pos"] as? [Any] { s.position = KVector(x: dbl(a[0]), y: dbl(a[1])) }
}

func makeLabels(_ list: Any?) -> [LLabel] {
    var out: [LLabel] = []
    for lo in (list as? [[String: Any]]) ?? [] {
        let l = LLabel(lo["text"] as! String)
        shape(l, lo)
        setProps(l, lo["props"])
        labelsByText[l.text] = l
        idOf[ObjectIdentifier(l)] = l.text
        out.append(l)
    }
    return out
}

let spec = try! JSONSerialization.jsonObject(with: try! Data(contentsOf: URL(fileURLWithPath: CommandLine.arguments[1]))) as! [String: Any]
let graph = LGraph()
let gspec = (spec["graph"] as? [String: Any]) ?? [:]
setProps(graph, gspec["props"])
if let a = gspec["size"] as? [Any] { graph.size = KVector(x: dbl(a[0]), y: dbl(a[1])) }

for no in (spec["nodes"] as? [[String: Any]]) ?? [] {
    let n = LNode(graph)
    let id = no["id"] as! String
    nodesById[id] = n; idOf[ObjectIdentifier(n)] = id
    if let t = no["type"] as? String { n.type = pick(t, [NodeType.normal, .longEdge, .externalPort, .northSouthPort, .label, .breakingPoint, .placeholder, .nonShiftingPlaceholder]) }
    shape(n, no)
    setProps(n, no["props"])
    if let m = no["margin"] as? [Any] { n.margin.top = dbl(m[0]); n.margin.right = dbl(m[1]); n.margin.bottom = dbl(m[2]); n.margin.left = dbl(m[3]) }
    n.labels = makeLabels(no["labels"])
    for po in (no["ports"] as? [[String: Any]]) ?? [] {
        let p = LPort()
        let pid = po["id"] as! String
        portsById[pid] = p; idOf[ObjectIdentifier(p)] = pid
        shape(p, po)
        p.setNode(n)
        p.setSide(pick(po["side"] as! String, [PortSide.UNDEFINED, .NORTH, .EAST, .SOUTH, .WEST]))
        if let a = po["anchor"] as? [Any] { p.anchor = KVector(x: dbl(a[0]), y: dbl(a[1])) }
        setProps(p, po["props"])
        p.labels = makeLabels(po["labels"])
    }
}
for eo in (spec["edges"] as? [[String: Any]]) ?? [] {
    let e = LEdge()
    let id = eo["id"] as! String
    edgesById[id] = e; idOf[ObjectIdentifier(e)] = id
    e.setSource(portsById[eo["source"] as! String]!)
    e.setTarget(portsById[eo["target"] as! String]!)
    setProps(e, eo["props"])
    e.labels = makeLabels(eo["labels"])
}
for lids in (spec["layers"] as? [[String]]) ?? [] {
    let layer = Layer(graph)
    graph.layers.append(layer)
    for nid in lids { nodesById[nid]!.setLayer(layer) }
}
for f in deferred { f() }

func name(_ o: AnyObject?) -> String { o.map { idOf[ObjectIdentifier($0)] ?? "?" } ?? "-" }
func opt(_ v: Any?) -> String {
    guard let v = v else { return "-" }
    if let x = v as? Double { return d(x) }
    if let x = v as? AnyObject, idOf[ObjectIdentifier(x)] != nil { return name(x) }
    return norm("\(v)")
}
func spacing(_ s: Spacing) -> String { "(\(d(s.top)),\(d(s.right)),\(d(s.bottom)),\(d(s.left)))" }
func labelLine(_ l: LLabel, _ indent: String) -> String {
    "\(indent)label \(l.text) pos=\(vec(l.position)) size=\(vec(l.size)) side=\(opt(l.getProperty(InternalProperties.LABEL_SIDE))) edge=\(opt(l.getProperty(InternalProperties.END_LABEL_EDGE)))\n"
}
func cellLine(_ c: LabelCell, _ indent: String) -> String {
    let r = c.cellRectangle
    return "\(indent)cell rect=(\(d(r.x)),\(d(r.y)),\(d(r.width)),\(d(r.height))) h=\(norm("\(c.horizontalAlignment)")) v=\(norm("\(c.verticalAlignment)")) labels=[\(c.labels.map { ($0 as! LGraphAdapters.LLabelAdapter).element.text }.joined(separator: ","))]\n"
}
func dump() -> String {
    var s = "graph size=\(vec(graph.size))\n"
    for (li, layer) in graph.layers.enumerated() {
        for n in layer.nodes {
            s += "L\(li) node \(name(n)) \(norm("\(n.type)")) id=\(n.id) pos=\(vec(n.position)) size=\(vec(n.size)) margin=\(spacing(n.margin)) padding=\(spacing(n.padding))\n"
            for l in n.labels { s += labelLine(l, "  ") }
            for p in n.ports {
                s += "  port \(name(p)) \(norm("\(p.side)")) id=\(p.id) pos=\(vec(p.position)) size=\(vec(p.size)) anchor=\(vec(p.anchor)) met=\(opt(p.getProperty(InternalProperties.MAX_EDGE_THICKNESS)))\n"
                for l in p.labels { s += labelLine(l, "    ") }
            }
            if let cells = n.getProperty(InternalProperties.END_LABELS) as? [LPort: LabelCell] {
                for p in n.ports { if let c = cells[p] { s += cellLine(c, "  endlabels \(name(p)) ") } }
            }
        }
    }
    for (id, e) in edgesById.sorted(by: { $0.key < $1.key }) {
        s += "edge \(id)\n"
        for l in e.labels { s += labelLine(l, "  ") }
    }
    return s
}

let monitor = BasicProgressMonitor()
var out = ""
for step in (spec["run"] as? [String]) ?? [] {
    let parts = step.split(separator: ":").map(String.init)
    switch parts[0] {
    case "LabelAndNodeSizeProcessor": org_eclipse_elk_alg_layered_intermediate_LabelAndNodeSizeProcessor().process(graph, monitor)
    case "InnermostNodeMarginCalculator": org_eclipse_elk_alg_layered_intermediate_InnermostNodeMarginCalculator().process(graph, monitor)
    case "EndLabelPreprocessor": org_eclipse_elk_alg_layered_intermediate_EndLabelPreprocessor().process(graph, monitor: monitor)
    case "EndLabelSorter": org_eclipse_elk_alg_layered_intermediate_EndLabelSorter().process(graph, monitor)
    case "EndLabelPostprocessor": org_eclipse_elk_alg_layered_intermediate_EndLabelPostprocessor().process(graph, monitor)
    case "LabelSideSelector": org_eclipse_elk_alg_layered_intermediate_LabelSideSelector().process(graph, monitor)
    case "MarginCalcNode":
        NodeDimensionCalculation.getNodeMarginCalculator(LGraphAdapters.adapt(graph, transparentNorthSouthEdges: false))
            .process(node: LGraphAdapters.adapt(nodesById[parts[1]]!, transparentNorthSouthEdges: false))
    case "InsidePadding":
        let p = NodeLabelAndSizeCalculator.computeInsideNodeLabelPadding(LGraphAdapters.adapt(graph), LGraphAdapters.adapt(nodesById[parts[1]]!, transparentNorthSouthEdges: false), pick(parts[2], [Direction.UNDEFINED, .RIGHT, .LEFT, .DOWN, .UP]))
        out += "insidePadding \(parts[1]) \(spacing(p))\n"
    case "SetPos":
        nodesById[parts[1]]!.position = KVector(x: Double(parts[2])!, y: Double(parts[3])!)
    case "Remover":
        // Remover:<direction>:<gapH>:<gapV>:<start>:x,y,w,h;x,y,w,h;...
        let dir = pick(parts[1], [RectangleStripOverlapRemover.OverlapRemovalDirection.up, .down, .left, .right])
        let remover = RectangleStripOverlapRemover.create(for: dir).withGap(Double(parts[2])!, Double(parts[3])!)
        var rects: [ElkRectangle] = []
        for r in parts[5].split(separator: ";") {
            let v = r.split(separator: ",").map { Double(String($0))! }
            let rect = ElkRectangle(x: v[0], y: v[1], width: v[2], height: v[3])
            rects.append(rect)
            remover.addRectangle(rect)
        }
        let size = remover.withStartCoordinate(Double(parts[4])!).removeOverlaps()
        out += "remover \(parts[1]) strip=\(d(size))\n"
        for r in rects { out += "  rect (\(d(r.x)),\(d(r.y)),\(d(r.width)),\(d(r.height)))\n" }
    case "Dump": out += "== \(parts.count > 1 ? parts[1] : "")\n" + dump()
    default: fatalError("unknown step \(step)")
    }
}
print(out, terminator: "")
