// Generates crates/core/src/swift_text/grapheme_tables.rs: the grapheme
// cluster break classes the Swift runtime actually uses, recovered from its
// observable behaviour (`String.count` in probing contexts), so Upleft's
// Character boundaries are Downright's by construction.
//
//   swift scripts/gen-grapheme-tables.swift > crates/core/src/swift_text/grapheme_tables.rs
//
// Swift's grapheme breaking (StringGraphemeBreaking.swift) differs from the
// Unicode tables other libraries ship in small ways (GB9c's linker set is the
// six Indic viramas; some Unicode 16 Grapheme_Cluster_Break=V assignments are
// absent), which is why the data comes from the runtime rather than the UCD.
import Foundation

func count(_ pieces: String...) -> Int { pieces.joined().count }

enum Class: UInt8 {
    case any = 0, cr, lf, control, extend, zwj, regionalIndicator, prepend, spacingMark
    case l, v, t, lv, lvt, extendedPictographic
}

func classify(_ scalar: Unicode.Scalar) -> (Class, Bool, Bool) {
    let s = String(Character(scalar))
    if scalar == "\r" { return (.cr, false, false) }
    if scalar == "\n" { return (.lf, false, false) }
    if scalar == "\u{200D}" { return (.zwj, false, count("\u{0915}", s, "\u{094D}\u{0915}") == 1) }
    let joinsAfterLetter = count("a", s) == 1
    if count(s, "\u{0301}") == 2 { return (.control, false, false) }
    if joinsAfterLetter {
        // Extend continues an emoji sequence (GB11); SpacingMark does not.
        let extend = count("\u{1F600}", s, "\u{200D}\u{1F600}") == 1
        let incbExtend = count("\u{0915}", s, "\u{094D}\u{0915}") == 1
        return (extend ? .extend : .spacingMark, false, incbExtend)
    }
    if count(s, "a") == 1 { return (.prepend, false, false) }
    let afterL = count("\u{1100}", s) == 1
    let afterLV = count("\u{AC00}", s) == 1
    let afterLVT = count("\u{AC01}", s) == 1
    let beforeV = count(s, "\u{1160}") == 1
    let beforeT = count(s, "\u{11A8}") == 1
    switch (afterL, afterLV, afterLVT, beforeV, beforeT) {
    case (true, false, false, true, false): return (.l, false, false)
    case (true, true, false, true, true): return (.v, false, false)
    case (false, true, true, false, true): return (.t, false, false)
    case (true, false, false, true, true): return (.lv, false, false)
    case (true, false, false, false, true): return (.lvt, false, false)
    default: break
    }
    if count("\u{1F1E6}", s) == 1 { return (.regionalIndicator, false, false) }
    let linkingConsonant = count("\u{0915}\u{094D}", s) == 1
    if count("\u{1F600}\u{200D}", s) == 1 { return (.extendedPictographic, linkingConsonant, false) }
    return (.any, linkingConsonant, false)
}

var classRanges: [(UInt32, UInt32, Class)] = []
var consonants: [(UInt32, UInt32)] = []
var incbExtends: [(UInt32, UInt32)] = []

func extend(_ ranges: inout [(UInt32, UInt32)], _ value: UInt32) {
    if let last = ranges.last, last.1 + 1 == value { ranges[ranges.count - 1].1 = value } else { ranges.append((value, value)) }
}

for value in UInt32(0)...0x10FFFF {
    guard let scalar = Unicode.Scalar(value) else { continue }
    let (cls, consonant, incb) = classify(scalar)
    if cls != .any {
        if let last = classRanges.last, last.1 + 1 == value, last.2 == cls {
            classRanges[classRanges.count - 1].1 = value
        } else {
            classRanges.append((value, value, cls))
        }
    }
    if consonant { extend(&consonants, value) }
    if incb { extend(&incbExtends, value) }
}

func hex(_ v: UInt32) -> String { "0x" + String(v, radix: 16, uppercase: true) }
let names: [Class: String] = [
    .cr: "CR", .lf: "LF", .control: "Control", .extend: "Extend", .zwj: "ZWJ",
    .regionalIndicator: "RegionalIndicator", .prepend: "Prepend", .spacingMark: "SpacingMark",
    .l: "L", .v: "V", .t: "T", .lv: "LV", .lvt: "LVT", .extendedPictographic: "ExtendedPictographic",
]

print("""
// @generated by scripts/gen-grapheme-tables.swift from the Swift runtime
// (\(ProcessInfo.processInfo.operatingSystemVersionString)). Do not edit.

use super::graphemes::GraphemeClass::{self, *};

/// Grapheme break class of every scalar that is not `Any`, as inclusive
/// ranges in ascending order.
pub static CLASSES: &[(u32, u32, GraphemeClass)] = &[
""")
for (lo, hi, cls) in classRanges { print("    (\(hex(lo)), \(hex(hi)), \(names[cls]!)),") }
print("];\n")
print("/// Scalars Swift treats as GB9c linking consonants.")
print("pub static LINKING_CONSONANTS: &[(u32, u32)] = &[")
for (lo, hi) in consonants { print("    (\(hex(lo)), \(hex(hi))),") }
print("];\n")
print("/// Extend/ZWJ scalars that continue a GB9c conjunct (Swift: non-zero ccc).")
print("pub static INCB_EXTEND: &[(u32, u32)] = &[")
for (lo, hi) in incbExtends { print("    (\(hex(lo)), \(hex(hi))),") }
print("];")
